### ISSUE TITLE
Contributing.md and readme.md suggestions

### ISSUE THREAD

**Issue by Ngoakor12** [matthewbub/calendar-widgets#87]
Here are some suggestions after having gone through both files:
- [ ] I don't believe the "local setup" section under the main `readme.md` is that important to include in the main page. Moving it to an appropriate section in `contributing.md`("contributing code" section could be the right place). It also frees up space for other exciting things to be showcased
- [ ] the "prerequisite" section in `contributing.md` sounds code related  and should perhaps be under "contributing code" as well
- [ ] under "contribution code"/"local setup" add installation and running commands for each package and mention which depend on which (this has been a pain, I was only able to run the docs package so far)

This I would like to work on, especially the installation and running part of each section once I get everything working. I can start tomorrow

**Comment by 9mbs** [comment]
Sure that works great for me! I can try to shed some light on which build commands are useful 

In `/workspaces/calendar-widgets` there are 3 relevant commands 

_/workspaces/calendar-widgets/package.json_

```js
"lint": "eslint ./src --ext .ts",
"lint:fix": "eslint ./src --ext .ts --fix",
"build": "rollup -c" /
```

The `start` script is useless. (I'll get a ticket created to remove that)

- :star: `build` if you make a change to the code in the `calendar-widgets` package, you'll need to recompile the code via `pnpm run build` 


_/workspaces/tests/package.json_

```js
"build:tests": "pnpm run build:calendar-widgets && pnpm run clean && pnpm run test"
```

Currently, the test directory is where you should be running commands from during development.

- `pnpm run build:tests` - The most accurate way to test changes during development. (Note: This does not lint the code) 
  1. Runs a build in the `workspaces/calendar-widgets` package
  2. Deletes and reinstalls the `calendar-widgets` package as a local depencdy in the `workspaces/tests` directory. 
  3. Runs the test suites

**Comment by 9mbs** [comment]
My only suggestion is that it should probably be emphasized that the `tests` directory is where we want to be running build commands from. This is because the test suites are the only way we can validate if the code in the package still works as expected.

**Comment by Ngoakor12** [comment]
> Sure that works great for me! I can try to shed some light on which build commands are useful
> 
> In `/workspaces/calendar-widgets` there are 3 relevant commands
> 
> _/workspaces/calendar-widgets/package.json_
> 
> ```js
> "lint": "eslint ./src --ext .ts",
> "lint:fix": "eslint ./src --ext .ts --fix",
> "build": "rollup -c" /
> ```
> 
> The `start` script is useless. (Created #88 to get that cleaned up)
> 
> * star `build` if you make a change to the code in the `calendar-widgets` package, you'll need to recompile the code via `pnpm run build`
> 
> _/workspaces/tests/package.json_
> 
> ```js
> "build:tests": "pnpm run build:calendar-widgets && pnpm run clean && pnpm run test"
> ```
> 
> Currently, the test directory is where you should be running commands from during development.
> 
> * `pnpm run build:tests` - The most accurate way to test changes during development. (Note: This does not lint the code)
>   
>   1. Runs a build in the `workspaces/calendar-widgets` package
>   2. Deletes and reinstalls the `calendar-widgets` package as a local depencdy in the `workspaces/tests` directory.
>   3. Runs the test suites

Thanks... I was able to run the tests eventually after the clean command.
