### ISSUE TITLE
remove the `start` script from Calendar-Widgets package

### ISSUE THREAD

**Issue by matthewbub** [matthewbub/calendar-widgets#88]
This is confusing and causing unnecessary difficulties for folks getting started locally. The `start` script within the `/workspaces/calendar-widgets/package.json` file does nothing at all and should be removed from the project. We only need the build and lint commands.

**Comment by Ankan-cyber** [comment]
@9mbs added pr for issue#88

**Comment by 9mbs** [comment]
Thank you @Ankan-cyber !! This should fix potential confusions when folks are pulling up the project locally. Closing this issue as the problem is resolved 🙂
